sudo: false
language: php

php:
  - 5.5
  - nightly
  - hhvm

cache:
  directories:
    - ~/.composer/cache

before_script:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/config:${SYMFONY_VERSION} symfony/dependency-injection:${SYMFONY_VERSION} symfony/event-dispatcher:${SYMFONY_VERSION} symfony/http-kernel:${SYMFONY_VERSION} symfony/framework-bundle:${SYMFONY_VERSION}; fi;
  - if [ "$SYMFONY_EVENT_DISPATCHER_VERSION" != "" ]; then composer require --no-update symfony/event-dispatcher:${SYMFONY_EVENT_DISPATCHER_VERSION}; fi;
  - composer install --no-interaction --prefer-source --dev

script: vendor/bin/phpunit --verbose

matrix:
  include:
    - php: 5.6
      env: [SYMFONY_VERSION="2.7.*", SYMFONY_EVENT_DISPATCHER_VERSION="2.7.*"]
    - php: 5.6
      env: [SYMFONY_VERSION="2.8.*", SYMFONY_EVENT_DISPATCHER_VERSION="2.8.*"]
    - php: 5.6
      env: [SYMFONY_VERSION="3.0.*", SYMFONY_EVENT_DISPATCHER_VERSION="3.0.*"]
    - php: 5.6
      env: [SYMFONY_VERSION="3.1.*", SYMFONY_EVENT_DISPATCHER_VERSION="3.1.*"]
    - php: 5.6
      env: [SYMFONY_VERSION="3.2.*", SYMFONY_EVENT_DISPATCHER_VERSION="3.2.*"]
    - php: 5.6
      env: [SYMFONY_VERSION="^3.3", SYMFONY_EVENT_DISPATCHER_VERSION="^3.3"]

    - php: 7.0
      env: [SYMFONY_VERSION="2.7.*", SYMFONY_EVENT_DISPATCHER_VERSION="2.7.*"]
    - php: 7.0
      env: [SYMFONY_VERSION="2.8.*", SYMFONY_EVENT_DISPATCHER_VERSION="2.8.*"]
    - php: 7.0
      env: [SYMFONY_VERSION="3.0.*", SYMFONY_EVENT_DISPATCHER_VERSION="3.0.*"]
    - php: 7.0
      env: [SYMFONY_VERSION="3.1.*", SYMFONY_EVENT_DISPATCHER_VERSION="3.1.*"]
    - php: 7.0
      env: [SYMFONY_VERSION="3.2.*", SYMFONY_EVENT_DISPATCHER_VERSION="3.2.*"]
    - php: 7.0
      env: [SYMFONY_VERSION="^3.3", SYMFONY_EVENT_DISPATCHER_VERSION="^3.3"]

    - php: 7.1
      env: [SYMFONY_VERSION="2.7.*", SYMFONY_EVENT_DISPATCHER_VERSION="2.7.*"]
    - php: 7.1
      env: [SYMFONY_VERSION="2.8.*", SYMFONY_EVENT_DISPATCHER_VERSION="2.8.*"]
    - php: 7.1
      env: [SYMFONY_VERSION="3.0.*", SYMFONY_EVENT_DISPATCHER_VERSION="3.0.*"]
    - php: 7.1
      env: [SYMFONY_VERSION="3.1.*", SYMFONY_EVENT_DISPATCHER_VERSION="3.1.*"]
    - php: 7.1
      env: [SYMFONY_VERSION="3.2.*", SYMFONY_EVENT_DISPATCHER_VERSION="3.2.*"]
    - php: 7.1
      env: [SYMFONY_VERSION="^3.3", SYMFONY_EVENT_DISPATCHER_VERSION="^3.3"]
    - php: 7.1
      env: [SYMFONY_VERSION="^4.0", SYMFONY_EVENT_DISPATCHER_VERSION="^4.0"]

  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true
